[project]
name = "sperms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onnxruntime>=1.25.0",
    "opencv-python>=4.13.0.92",
]
